name: unity-activation
on:
  workflow_dispatch: {}
jobs:
  activiation:
    name: Request activation file
    runs-on: ubuntu-latest
    steps:
      - name: Request file
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 2020.3.26f1
      - name: Expose artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
